### PR TITLE
Added initial support for Obsidian daily notes to Tana Calendar notes

### PR DESCRIPTION
**Pull request by vicrdguez**
Added additional parameter to specify the daily note pattern used for daily notes. It uses the same format as Obsidian using [moment](https://momentjs.com/docs/#/displaying/format/).

The translation is based on the assumption that calendar notes are of type `date` and the `uid` is the same as the name (a date) in MM-DD-YYYY format. Like the followiing:

```json
{
      "uid": "09-07-2022",
      "name": "09-07-2022",
      "children": [
        {
          "uid": "ZWWrfuNpM",
          "name": "Today I will write about [[59QkLn2qT]]",
          "children": [],
          "createdAt": 1662544333148,
          "editedAt": 1662544339648,
          "refs": [
            "59QkLn2qT"
          ],
          "type": "node"
        }
      ],
      "createdAt": 1662544329798,
      "editedAt": 1662544329798,
      "refs": [],
      "type": "date"
    },
```

Added also new tests to verify new code. `fileConverter.test` fails with an error also present in the existing test. I had no time to figure it out:

```
  - Expected  - 0
    + Received  + 6

    @@ -94,6 +94,12 @@
          "fields": 0,
          "leafNodes": 9,
          "topLevelNodes": 1,
          "totalNodes": 10,
        },
    +   Array [
    +     "heading",
    +     "Some",
    +     "Link",
    +     "Link2",
    +   ],
      ]
```

I have limited knowledge of TS so feel free to point all the obvious stuff that I may have made.
Thanks!

### CODE REVIEW

**Comment by LuccaHellriegel** [comment]
hey, very cool that you did this! Totally forgot about Daily Page conersion until now.
However, unfortunatley I shuffled quite a lot of stuff around to enable folder-structure based conversion and some other features. If nothing major is wrong with my approach, the structure should be fairly stable now.

On the positive side, I think most of your changes should be transferable to the new structure because the central functions are mostly similar, so its best if you re-fork and add your changes in the new structure. If you want, I can add them too - but then you wouldnt show up as contributor.

As for the changes itself: I removed uid = name everywhere and replaced it with a uidRequest method.
I think another approach for the date-format might be to read Obsidians DailyNotes settings - I think this might be more promising than giving it as a format.

**Comment by vicrdguez** [comment]
Hi @LuccaHellriegel, no Issues, I started solving conflicts with the first commits you did but I were not able to get the time to finish them before you pushed the next set of changes 😅 . No Issues at all I was planning to adapt to your changes since you know the core structure of the converter much more than me. 

As said the first set of conflicts are resolved already I will try to resolve your new changes today. 

As per the date format, I think its a great idea to read the config directly from obsidian! However I think is still valuable to have an optional parameter, since I know people that have an obsidian vault but no obsidian installed. What do you think?

**Comment by vicrdguez** [comment]
Hi @LuccaHellriegel, I've resolved all the conflicts (including the ones appearing during these days). Take a look and let me know if it looks good,

**Comment by vicrdguez** [comment]
Ah, also now the daily note pattern is taken from obsidian config files, not taken by cli argument

**Comment by LuccaHellriegel** [comment]
Hi @vicrdguez , thanks for the great work getting the merge conflicts fixed and reading from the obsidian folder.

Just four more little things:
* could you remove the fs-call from the vault context? The filesystem calls will be replaced with an adapter sooner or later which supports local + browser environements and I think it does not need to be in the constructor, for simplicities sake you could just set the public dailyNoteFormat prop after the call
* please check the vault converter test, I am sure with your changes it will fail, so the full.tif.json needs to be adapted
* I also see some unformatted code, could you re-format everything with prettier please? 
* at the end, could you squash the commits to be only one daily notes commit? I want to keep the history as clean as possible to increase chances of merging it into the official repo at some point

**Pull request closed without merging**
